github: []
patreon: "bsanju"
open_collective: []
ko_fi: "bsanju"
tidelift: []
community_bridge: []
liberapay: []
issuehunt: []
lfx_crowdfunding: []
polar: []
buy_me_a_coffee: "bsanju"
thanks_dev: "bsanjuu"
custom: ["https://www.patreon.com/c/bsanju?fromConcierge=true", "https://thanks.dev/bsanjuu", "https://buymeacoffee.com/bsanju", "https://ko-fi.com/bsanju"]
